data_path: examples/sample_data.csv
target: label
models:
  - name: random_forest
    params:
      n_estimators: 100
      max_depth: 5
  - name: logistic_regression
    params:
      solver: liblinear
test_size: 0.2
random_state: 42
metrics: [accuracy, f1]